#!/usr/bin/env bash

# $HOME/bin

clear
#sudo dnf upgrade --refresh 
#[[ ! sudo dnf upgrade --refresh ]] && read -r -p 'Upgrade failed!' && exit 1
if ! sudo dnf upgrade --refresh
then
	read -r -p 'Upgrade failed'
	exit 1
fi
echo
#read -r -p 'Press Enter to continue'

clear
dnf needs-restarting
[[ $? == 1 ]] && reboot
echo
#read -r -p 'Do you want to reboot? (y/N) '
#[[ $REPLY == y ]] && reboot
echo
read -r -p 'Press Enter to continue'

clear
flatpak list --verbose
echo
read -r -p 'Press Enter to continue'

clear
fwupdmgr refresh
echo
fwupdmgr update
echo

read -r -p 'End of updates!'

